1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix} -1 & -6\\ 2 & 6 \end{pmatrix}.$$

Тсобственные значения линейного оператора

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(6-\lambda)-(-6)\cdot2=0,$$

$$\lambda^{2}-5\cdot\lambda+6=0,$$

$$\lambda_{1}=2$$   $$\lambda_{2}=3.$$

$\begin{pmatrix} -1 & -6\\ 2 & 6 \end{pmatrix}$ $\cdot$ $\begin{pmatrix} х_1 \\ х_2 \end{pmatrix}$
= $\lambda$ $\cdot$ $\begin{pmatrix} х_1 \\ х_2 \end{pmatrix}$

$\begin{pmatrix} -1 & -6\\ 2 & 6 \end{pmatrix}$ $\cdot$ $\begin{pmatrix} х_1 \\ х_2 \end{pmatrix}$
=  $\begin{pmatrix} 2\cdotх_1 \\ 2\cdotх_2 \end{pmatrix}$

$$\begin{cases}
-1 \cdot x_{1}+ -6 \cdot x_{2}= 2 \cdot x_{1}, \\
2 \cdot x_{1}+6 \cdot x_{2}= 2 \cdot x_{2}.
\end{cases}$$ 

$$ x_{1} = -2 \cdot x_{2} $$ 

$\begin{pmatrix} -1 & -6\\ 2 & 6 \end{pmatrix}$ $\cdot$ $\begin{pmatrix} х_1 \\ х_2 \end{pmatrix}$
=  $\begin{pmatrix} 3\cdotх_1 \\ 3\cdotх_2 \end{pmatrix}$

$$\begin{cases}
-1 \cdot x_{1}+ -6 \cdot x_{2}= 3 \cdot x_{1}, \\
2 \cdot x_{1}+6 \cdot x_{2}= 3 \cdot x_{2}.
\end{cases}$$ 

$$\begin{cases}
-6 \cdot x_{2}= 4 \cdot x_{1}, \\
3 \cdot x_{2}= -2 \cdot x_{1}.
\end{cases}$$ 

$$x_{1} = -\frac{3}{2} \cdot x_{2}$$

$x=$ 
$\begin{pmatrix} -2 & -\frac{3}{2}\\ 1 & 1 \end{pmatrix} $

In [1]:
import numpy as np
A = np.array([
    [-1, -6], 
    [2, 6]
])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')



Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

собственные значения линейного оператора

$$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(-1-\lambda)-0=0,$$

$$\lambda=-1$$

$\begin{pmatrix} -1 & 0\\ 0 & -1 \end{pmatrix}$ $\cdot$ $\begin{pmatrix} х_1 \\ х_2 \end{pmatrix}$
= $\lambda$ $\cdot$ $\begin{pmatrix} х_1 \\ х_2 \end{pmatrix}$

$\begin{pmatrix} -1 & 0\\ 0 & -1 \end{pmatrix}$ $\cdot$ $\begin{pmatrix} х_1 \\ х_2 \end{pmatrix}$
=  $\begin{pmatrix} -х_1 \\ -х_2 \end{pmatrix}$

$$\begin{cases}
-1 \cdot x_{1} = -x_{1}, \\
-1 \cdot x_{2}= -x_{2}.
\end{cases}$$ 

__любой__ вектор является для него собственным.

In [2]:
A = np.array([
    [-1, 0], 
    [0, -1]
])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$\begin{pmatrix} 1 & 1\\ -1 & 3 \end{pmatrix}$ $\cdot$ $\begin{pmatrix} 1 \\ 1 \end{pmatrix}$
= $\lambda$ $\cdot$ $\begin{pmatrix} 1 \\ 1 \end{pmatrix}$

$\begin{pmatrix} 1 & 1\\ -1 & 3 \end{pmatrix}$ $\cdot$ $\begin{pmatrix} 1 \\ 1 \end{pmatrix}$
= $\begin{pmatrix} \lambda \\ \lambda \end{pmatrix}$

$$\begin{cases}
1 + 1 = \lambda, \\
-1 + 3 = \lambda.
\end{cases}$$ 

$$\lambda = 2$$

да

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}$
$\cdot$
$\begin{pmatrix} 3 \\ -3 \\ -4 \end{pmatrix}$
$=$
$\begin{pmatrix} 3\cdot \lambda \\ -3\cdot \lambda \\ -4\cdot \lambda \end{pmatrix}$

$$\begin{cases}
-3 \cdot 3 = 3 \cdot \lambda, \\
3 \cdot 3= -3 \cdot \lambda, \\
-4 \cdot 3= -4 \cdot \lambda.
\end{cases}$$ 

$$\begin{cases}
-3 = \lambda, \\
-3 = \lambda, \\
3=  \lambda.
\end{cases}$$ 

Нет