1. Установить, какие произведения матриц 𝐴𝐵 и 𝐵𝐴

определены, и найти размерности полученных матриц:

а) 𝐴 — матрица 4×2, 𝐵 — матрица 4×2;

𝐴𝐵 - невозможно
BA - невозможно

1. Установить, какие произведения матриц 𝐴𝐵 и 𝐵𝐴 определены, и найти размерности полученных матриц:

б) 𝐴
— матрица 2×5, 𝐵 — матрица 5×3;

𝐴𝐵 - 2×3
BA - невозможно

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

$AB$ - $8\times 8$

$BA$ - $3\times 3$

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

$AB$ — квадратная матрица $4\times 4$

$BA$ — квадратная матрица $4\times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+B$ = $\begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix}$ 
=
$\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$ 

$A*B$ = $\begin{pmatrix}
1*4-2*0 & -1*1-2*5\\ 
3*4+0*0 & -3*1+5*0
\end{pmatrix}$ 
=
$\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [1]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(A + B)
print(np.dot(A, B))

[[ 5 -3]
 [ 3  5]]
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A$ = $\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$ 

$2B$ = $\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$ 

$4C$ = $\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$ 

$3A-2B+4C$ = $\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$ 

In [2]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
3*A-2*B+4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\end{pmatrix}$

$AA^{T}$ = 
$\begin{pmatrix}
4*4+1*1 & 4*5-1*2 & 4*2+1*3\\ 
5*4+-1*2 & 5*5+2*2 & 5*2-2*3\\ 
2*4+3*1 & 2*5-3*2 & 2*2+3*3\end{pmatrix}$
=$\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13\end{pmatrix}$

$A^{T}A$ = 
$\begin{pmatrix}
4*4+5*5+2*2 & 4*1-5*2+2*3\\ 
1*4-5*2+3*2 & 1*1+2*2+3*3\end{pmatrix}$
= 
$\begin{pmatrix}
45 & 0\\ 
0 & 14\end{pmatrix}$

In [3]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [4]:
print(A@A.T)
print(A.T@A)

[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
def dotmatrix(A, B):
 
    if (len(A) != len(B[0])) or len(A) == 0 or len(B) == 0:
        return None
 
    result = [[0] * len(B[0]) for i in range(len(A))]
    
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

In [6]:
A = [[1, -2], 
     [3, 0]]

B = [[4, -1], 
     [0, 5]]

res = dotmatrix(A, B)
res

[[4, -11], [12, -3]]

In [7]:
A = [[4, 1], [5, -2], [2, 3]]
B = [[ 4,  5,  2], [ 1, -2,  3]]

res = dotmatrix(A, B)
res

[[17, 18, 11], [18, 29, 4], [11, 4, 13]]

In [8]:
res = dotmatrix(B, A)
res

[[45, 0], [0, 14]]

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$


$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}$ 
=
$sinx*sinx - (-cosx)*cosx$ =1

__1.__ Вычислить определитель:

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}$
=$4 * 5 * 9$=$180$

In [9]:
A = [[4, 2, 3],
     [0, 5, 1],
     [0, 0, 9]]
np.linalg.det(A)

180.0

__1.__ Вычислить определитель:
в)
$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}$
=
$\begin{vmatrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
7 & 8 & 9
\end{vmatrix}$
=
$(-1)^{2+1}*2*$$\begin{vmatrix}
2 & 3\\
8 & 9
\end{vmatrix}$
+
$(-1)^{2+2}*1*$$\begin{vmatrix}
1 & 3\\
7 & 9
\end{vmatrix}$
+
$0$
=
$-2*(18-24) + 1*(9-21)$
=$0$

In [10]:
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
np.linalg.det(A)

6.66133814775094e-16

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;

__9.__ Для двух квадратных матриц одинакового размера

$$det(AB)=detA\cdot detB.$$

$det(A^{2}) = 16$;

__2.__ Определитель матрицы $A$ равен $4$. Найти:
    
   б) $det(A^{T})$;

__1.__ Определитель транспонированной матрицы равен определителю исходной:

$$detA^{T}=detA.$$
$det(A^{T})=4$

__2.__ Определитель матрицы $A$ равен $4$. Найти:
    
   в) $det(2A)$.

Первое опорное правило:

Умножение матрицы на число происходит так же просто, как и сложение: _произведением матрицы_ $A=\left\|a_{ij}\right\|$ на число $\lambda$ является матрица $C = \left\|c_{ij}\right\|$, элементы которой $c_{ij}=\lambda a_{ij}$, то есть каждый элемент матрицы умножается на число $\lambda$:

$$\lambda\cdot\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
a_{21} & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
a_{m1} & a_{m2} & \cdots & a_{mn}\\ 
\end{pmatrix}=
\begin{pmatrix}
\lambda a_{11} & \lambda a_{12} & \cdots & \lambda a_{1n}\\ 
\lambda a_{21} & \lambda a_{22} & \cdots & \lambda a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
\lambda a_{m1} & \lambda a_{m2} & \cdots & \lambda a_{mn}\\ 
\end{pmatrix}.$$

Второе опорное правило:

__2.__ Умножение строки или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число. 

- Доказательство этого свойства элементарно, так как, исходя из формулы определителя, множитель из этой строки будет в каждом из слагаемых при нахождении определителя разложением по этой строке/столбцу, что равнозначно его умножению на это число.

Для квадратной матрицы размером $n$

$det(2A)$ = $det(A) *2^{n}$

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Первую строку $*2$ и прибавить ко второй

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$
=
$\begin{pmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{pmatrix}$

__6.__ Если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю.

$$det\begin{vmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{vmatrix}=0$$

In [11]:
A = [[-2, 7, -3],
     [4, -14, 6],
     [-3, 7, 13]]
np.linalg.det(A)

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

3 строка является суммой 1 и 2 строк, а значит, ее можно отбросить:

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix};$

Из 1 строки вычтем 2:

$\begin{pmatrix}
0 & 1 & 2\\ 
1 & 1 & 1
\end{pmatrix};$

Таким образом, ранг матрицы равен $2$.

In [12]:
A = [[1, 2, 3],
     [1, 1, 1],
     [2, 3, 4]]
np.linalg.matrix_rank(A)

2

__4.__ Найти ранг матрицы:

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

3 строка является суммой 1 и 2 строк, а значит, ее можно отбросить:

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Из 1 строки вычтем 2 строку, $*-1$:

$\begin{pmatrix}
0 & 0 & 0 & -1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Таким образом, ранг матрицы равен $3$.

In [13]:
A = [[0, 0, 2, 1],
     [0, 0, 2, 2],
     [0, 0, 4, 3],
     [2, 3, 5, 6]]
np.linalg.matrix_rank(A)

3