1. Установить, какие произведения матриц 𝐴𝐵 и 𝐵𝐴

определены, и найти размерности полученных матриц:

а) 𝐴 — матрица 4×2, 𝐵 — матрица 4×2;

𝐴𝐵 - невозможно
BA - невозможно

1. Установить, какие произведения матриц 𝐴𝐵 и 𝐵𝐴 определены, и найти размерности полученных матриц:

б) 𝐴
— матрица 2×5, 𝐵 — матрица 5×3;

𝐴𝐵 - 2×3
BA - невозможно

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

$AB$ - $8\times 8$

$BA$ - $3\times 3$

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

$AB$ — квадратная матрица $4\times 4$

$BA$ — квадратная матрица $4\times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+B$ = $\begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix}$ 
=
$\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$ 

$A*B$ = $\begin{pmatrix}
1*4-2*0 & -1*1-2*5\\ 
3*4+0*0 & -3*1+5*0
\end{pmatrix}$ 
=
$\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [7]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(A + B)
print(np.dot(A, B))

[[ 5 -3]
 [ 3  5]]
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A$ = $\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$ 

$2B$ = $\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$ 

$4C$ = $\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$ 

$3A-2B+4C$ = $\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$ 

In [9]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
3*A-2*B+4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\end{pmatrix}$

$AA^{T}$ = 
$\begin{pmatrix}
4*4+1*1 & 4*5-1*2 & 4*2+1*3\\ 
5*4+-1*2 & 5*5+2*2 & 5*2-2*3\\ 
2*4+3*1 & 2*5-3*2 & 2*2+3*3\end{pmatrix}$
=$\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13\end{pmatrix}$

$A^{T}A$ = 
$\begin{pmatrix}
4*4+5*5+2*2 & 4*1-5*2+2*3\\ 
1*4-5*2+3*2 & 1*1+2*2+3*3\end{pmatrix}$
= 
$\begin{pmatrix}
45 & 0\\ 
0 & 14\end{pmatrix}$

In [12]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [15]:
print(A@A.T)
print(A.T@A)

[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [51]:
def dotmatrix(A, B):
 
    if (len(A) != len(B[0])) or len(A) == 0 or len(B) == 0:
        return None
 
    result = [[0] * len(B[0]) for i in range(len(A))]
    
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

In [53]:
A = [[1, -2], 
     [3, 0]]

B = [[4, -1], 
     [0, 5]]

res = dotmatrix(A, B)
res

[[4, -11], [12, -3]]

In [54]:
A = [[4, 1], [5, -2], [2, 3]]
B = [[ 4,  5,  2], [ 1, -2,  3]]

res = dotmatrix(A, B)
res

[[17, 18, 11], [18, 29, 4], [11, 4, 13]]

In [55]:
res = dotmatrix(B, A)
res

[[45, 0], [0, 14]]